name: 'Nounish RLE Action'
description: 'Run-length encode 32x32 PNG Noun trait images and write the result to a file'
author: 'solimander'
inputs:
  rootDirectoryPath:
    required: true
    description: 'Path to the directory that contains the Noun part folders'
  outputPath:
    required: true
    description: 'Path to output the run-length encoded Noun data'
runs:
  using: 'node14'
  main: 'dist/index.js'
